### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by RetroGameTalk** [StrawberryPerl/strawberryperl.com#37]
solved

**Comment by shawnlaffan** [comment]
The releases on strawberryperl.com are yet to be updated.  If you want the latest versions then see https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/

Also, there is no need to edit the issue title or main text when closing an issue.  This removes any context and makes it hard to see what the issue was about when looking at the list of issues.  It is better to add a comment and then close.
